// Generated by gen-tool
// DO NOT EDIT!
package auto

import (
	"reflect"
	"github.com/Blizzardx/GoConfigTool/configManager"
)

func init() {

	configManager.RegisterType(reflect.TypeOf((*WGQueryPlayerInfos)(nil)).Elem())

	configManager.RegisterType(reflect.TypeOf((*WGAddMoney)(nil)).Elem())

	configManager.RegisterType(reflect.TypeOf((*WGPaymentSuccess)(nil)).Elem())

	configManager.RegisterType(reflect.TypeOf((*GWAddMoney)(nil)).Elem())

	configManager.RegisterType(reflect.TypeOf((*WorldPlayerInfo)(nil)).Elem())

	configManager.RegisterType(reflect.TypeOf((*WorldApplyCreateLeagueInfo)(nil)).Elem())

}
